#!/bin/bash

# Define your GitHub username and token
GITHUB_USERNAME="your username"
GITHUB_TOKEN="your access token"

# Set the GitHub repository URL
REPO_URL="https://github.com/jamangi/programming-quizzes.git"

# Configure Git to use the credential helper
git config credential.helper store
echo -e "protocol=https\nhost=github.com\nusername=$GITHUB_USERNAME\npassword=$GITHUB_TOKEN" | git credential approve

# Perform the Git operations
git add .
git reset push # this ensures your changes to push are not pushed to the repo, for security
git commit -m "Scheduled Update"

# Push to GitHub without entering credentials
git push "$REPO_URL"

